AAAAAAAA=;;=AAAAAAAA
AAAAAAAA=  =AAAAAAAA
AAAAAAAA=  =AAAAAAAA
AAAAAAAA=  =AAAAAAAA
AAAAAAAA=  =AAAAAAAA
AAAAA====  ====AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA=        =AAAAA
AAAAA==========AAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAA