zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       ===z
zzz=         =z
zzz=         =z
zzz=         =z
zzz=         =z
zzz= :     ===z
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz
zzz=       =zzz